geany .gitignore -l 1 # < .gitignore:1:# samurai_ide specific
geany .gitignore -l 2 # < .gitignore:2:samurai_ide/addins/plugins/*
geany samurai-ide.ts -l 6 # < samurai-ide.ts:6:        <location filename="samurai_ide/translations.py" line="9"/>
geany samurai-ide.ts -l 12 # < samurai-ide.ts:12:        <location filename="samurai_ide/translations.py" line="10"/>
geany samurai-ide.ts -l 18 # < samurai-ide.ts:18:        <location filename="samurai_ide/translations.py" line="11"/>
geany samurai-ide.ts -l 24 # < samurai-ide.ts:24:        <location filename="samurai_ide/translations.py" line="12"/>
geany samurai-ide.ts -l 30 # < samurai-ide.ts:30:        <location filename="samurai_ide/translations.py" line="13"/>
geany samurai-ide.ts -l 36 # < samurai-ide.ts:36:        <location filename="samurai_ide/translations.py" line="14"/>
geany samurai-ide.ts -l 42 # < samurai-ide.ts:42:        <location filename="samurai_ide/translations.py" line="15"/>
geany samurai-ide.ts -l 48 # < samurai-ide.ts:48:        <location filename="samurai_ide/translations.py" line="18"/>
geany samurai-ide.ts -l 54 # < samurai-ide.ts:54:        <location filename="samurai_ide/translations.py" line="19"/>
geany samurai-ide.ts -l 60 # < samurai-ide.ts:60:        <location filename="samurai_ide/translations.py" line="20"/>
geany samurai-ide.ts -l 66 # < samurai-ide.ts:66:        <location filename="samurai_ide/translations.py" line="21"/>
geany samurai-ide.ts -l 72 # < samurai-ide.ts:72:        <location filename="samurai_ide/translations.py" line="22"/>
geany samurai-ide.ts -l 78 # < samurai-ide.ts:78:        <location filename="samurai_ide/translations.py" line="23"/>
geany samurai-ide.ts -l 84 # < samurai-ide.ts:84:        <location filename="samurai_ide/translations.py" line="24"/>
geany samurai-ide.ts -l 90 # < samurai-ide.ts:90:        <location filename="samurai_ide/translations.py" line="25"/>
geany samurai-ide.ts -l 96 # < samurai-ide.ts:96:        <location filename="samurai_ide/translations.py" line="26"/>
geany samurai-ide.ts -l 102 # < samurai-ide.ts:102:        <location filename="samurai_ide/translations.py" line="27"/>
geany samurai-ide.ts -l 108 # < samurai-ide.ts:108:        <location filename="samurai_ide/translations.py" line="28"/>
geany samurai-ide.ts -l 114 # < samurai-ide.ts:114:        <location filename="samurai_ide/translations.py" line="29"/>
geany samurai-ide.ts -l 120 # < samurai-ide.ts:120:        <location filename="samurai_ide/translations.py" line="30"/>
geany samurai-ide.ts -l 126 # < samurai-ide.ts:126:        <location filename="samurai_ide/translations.py" line="31"/>
geany samurai-ide.ts -l 132 # < samurai-ide.ts:132:        <location filename="samurai_ide/translations.py" line="32"/>
geany samurai-ide.ts -l 138 # < samurai-ide.ts:138:        <location filename="samurai_ide/translations.py" line="33"/>
geany samurai-ide.ts -l 144 # < samurai-ide.ts:144:        <location filename="samurai_ide/translations.py" line="34"/>
geany samurai-ide.ts -l 150 # < samurai-ide.ts:150:        <location filename="samurai_ide/translations.py" line="35"/>
geany samurai-ide.ts -l 156 # < samurai-ide.ts:156:        <location filename="samurai_ide/translations.py" line="36"/>
geany samurai-ide.ts -l 162 # < samurai-ide.ts:162:        <location filename="samurai_ide/translations.py" line="37"/>
geany samurai-ide.ts -l 168 # < samurai-ide.ts:168:        <location filename="samurai_ide/translations.py" line="38"/>
geany samurai-ide.ts -l 174 # < samurai-ide.ts:174:        <location filename="samurai_ide/translations.py" line="39"/>
geany samurai-ide.ts -l 180 # < samurai-ide.ts:180:        <location filename="samurai_ide/translations.py" line="40"/>
geany samurai-ide.ts -l 186 # < samurai-ide.ts:186:        <location filename="samurai_ide/translations.py" line="41"/>
geany samurai-ide.ts -l 192 # < samurai-ide.ts:192:        <location filename="samurai_ide/translations.py" line="42"/>
geany samurai-ide.ts -l 198 # < samurai-ide.ts:198:        <location filename="samurai_ide/translations.py" line="43"/>
geany samurai-ide.ts -l 204 # < samurai-ide.ts:204:        <location filename="samurai_ide/translations.py" line="44"/>
geany samurai-ide.ts -l 210 # < samurai-ide.ts:210:        <location filename="samurai_ide/translations.py" line="45"/>
geany samurai-ide.ts -l 216 # < samurai-ide.ts:216:        <location filename="samurai_ide/translations.py" line="46"/>
geany samurai-ide.ts -l 222 # < samurai-ide.ts:222:        <location filename="samurai_ide/translations.py" line="47"/>
geany samurai-ide.ts -l 228 # < samurai-ide.ts:228:        <location filename="samurai_ide/translations.py" line="48"/>
geany samurai-ide.ts -l 234 # < samurai-ide.ts:234:        <location filename="samurai_ide/translations.py" line="49"/>
geany samurai-ide.ts -l 240 # < samurai-ide.ts:240:        <location filename="samurai_ide/translations.py" line="50"/>
geany samurai-ide.ts -l 246 # < samurai-ide.ts:246:        <location filename="samurai_ide/translations.py" line="51"/>
geany samurai-ide.ts -l 252 # < samurai-ide.ts:252:        <location filename="samurai_ide/translations.py" line="52"/>
geany samurai-ide.ts -l 258 # < samurai-ide.ts:258:        <location filename="samurai_ide/translations.py" line="53"/>
geany samurai-ide.ts -l 264 # < samurai-ide.ts:264:        <location filename="samurai_ide/translations.py" line="54"/>
geany samurai-ide.ts -l 270 # < samurai-ide.ts:270:        <location filename="samurai_ide/translations.py" line="55"/>
geany samurai-ide.ts -l 276 # < samurai-ide.ts:276:        <location filename="samurai_ide/translations.py" line="56"/>
geany samurai-ide.ts -l 282 # < samurai-ide.ts:282:        <location filename="samurai_ide/translations.py" line="406"/>
geany samurai-ide.ts -l 288 # < samurai-ide.ts:288:        <location filename="samurai_ide/translations.py" line="58"/>
geany samurai-ide.ts -l 294 # < samurai-ide.ts:294:        <location filename="samurai_ide/translations.py" line="59"/>
geany samurai-ide.ts -l 300 # < samurai-ide.ts:300:        <location filename="samurai_ide/translations.py" line="60"/>
geany samurai-ide.ts -l 306 # < samurai-ide.ts:306:        <location filename="samurai_ide/translations.py" line="61"/>
geany samurai-ide.ts -l 312 # < samurai-ide.ts:312:        <location filename="samurai_ide/translations.py" line="62"/>
geany samurai-ide.ts -l 318 # < samurai-ide.ts:318:        <location filename="samurai_ide/translations.py" line="63"/>
geany samurai-ide.ts -l 324 # < samurai-ide.ts:324:        <location filename="samurai_ide/translations.py" line="64"/>
geany samurai-ide.ts -l 330 # < samurai-ide.ts:330:        <location filename="samurai_ide/translations.py" line="65"/>
geany samurai-ide.ts -l 336 # < samurai-ide.ts:336:        <location filename="samurai_ide/translations.py" line="66"/>
geany samurai-ide.ts -l 342 # < samurai-ide.ts:342:        <location filename="samurai_ide/translations.py" line="67"/>
geany samurai-ide.ts -l 348 # < samurai-ide.ts:348:        <location filename="samurai_ide/translations.py" line="68"/>
geany samurai-ide.ts -l 354 # < samurai-ide.ts:354:        <location filename="samurai_ide/translations.py" line="69"/>
geany samurai-ide.ts -l 360 # < samurai-ide.ts:360:        <location filename="samurai_ide/translations.py" line="70"/>
geany samurai-ide.ts -l 366 # < samurai-ide.ts:366:        <location filename="samurai_ide/translations.py" line="71"/>
geany samurai-ide.ts -l 372 # < samurai-ide.ts:372:        <location filename="samurai_ide/translations.py" line="72"/>
geany samurai-ide.ts -l 378 # < samurai-ide.ts:378:        <location filename="samurai_ide/translations.py" line="73"/>
geany samurai-ide.ts -l 384 # < samurai-ide.ts:384:        <location filename="samurai_ide/translations.py" line="257"/>
geany samurai-ide.ts -l 390 # < samurai-ide.ts:390:        <location filename="samurai_ide/translations.py" line="75"/>
geany samurai-ide.ts -l 396 # < samurai-ide.ts:396:        <location filename="samurai_ide/translations.py" line="76"/>
geany samurai-ide.ts -l 402 # < samurai-ide.ts:402:        <location filename="samurai_ide/translations.py" line="77"/>
geany samurai-ide.ts -l 408 # < samurai-ide.ts:408:        <location filename="samurai_ide/translations.py" line="78"/>
geany samurai-ide.ts -l 414 # < samurai-ide.ts:414:        <location filename="samurai_ide/translations.py" line="79"/>
geany samurai-ide.ts -l 420 # < samurai-ide.ts:420:        <location filename="samurai_ide/translations.py" line="80"/>
geany samurai-ide.ts -l 426 # < samurai-ide.ts:426:        <location filename="samurai_ide/translations.py" line="81"/>
geany samurai-ide.ts -l 432 # < samurai-ide.ts:432:        <location filename="samurai_ide/translations.py" line="82"/>
geany samurai-ide.ts -l 438 # < samurai-ide.ts:438:        <location filename="samurai_ide/translations.py" line="83"/>
geany samurai-ide.ts -l 444 # < samurai-ide.ts:444:        <location filename="samurai_ide/translations.py" line="84"/>
geany samurai-ide.ts -l 450 # < samurai-ide.ts:450:        <location filename="samurai_ide/translations.py" line="85"/>
geany samurai-ide.ts -l 456 # < samurai-ide.ts:456:        <location filename="samurai_ide/translations.py" line="86"/>
geany samurai-ide.ts -l 462 # < samurai-ide.ts:462:        <location filename="samurai_ide/translations.py" line="87"/>
geany samurai-ide.ts -l 468 # < samurai-ide.ts:468:        <location filename="samurai_ide/translations.py" line="88"/>
geany samurai-ide.ts -l 474 # < samurai-ide.ts:474:        <location filename="samurai_ide/translations.py" line="89"/>
geany samurai-ide.ts -l 480 # < samurai-ide.ts:480:        <location filename="samurai_ide/translations.py" line="90"/>
geany samurai-ide.ts -l 486 # < samurai-ide.ts:486:        <location filename="samurai_ide/translations.py" line="91"/>
geany samurai-ide.ts -l 492 # < samurai-ide.ts:492:        <location filename="samurai_ide/translations.py" line="92"/>
geany samurai-ide.ts -l 498 # < samurai-ide.ts:498:        <location filename="samurai_ide/translations.py" line="93"/>
geany samurai-ide.ts -l 504 # < samurai-ide.ts:504:        <location filename="samurai_ide/translations.py" line="94"/>
geany samurai-ide.ts -l 510 # < samurai-ide.ts:510:        <location filename="samurai_ide/translations.py" line="95"/>
geany samurai-ide.ts -l 516 # < samurai-ide.ts:516:        <location filename="samurai_ide/translations.py" line="96"/>
geany samurai-ide.ts -l 522 # < samurai-ide.ts:522:        <location filename="samurai_ide/translations.py" line="98"/>
geany samurai-ide.ts -l 528 # < samurai-ide.ts:528:        <location filename="samurai_ide/translations.py" line="99"/>
geany samurai-ide.ts -l 534 # < samurai-ide.ts:534:        <location filename="samurai_ide/translations.py" line="100"/>
geany samurai-ide.ts -l 540 # < samurai-ide.ts:540:        <location filename="samurai_ide/translations.py" line="101"/>
geany samurai-ide.ts -l 546 # < samurai-ide.ts:546:        <location filename="samurai_ide/translations.py" line="102"/>
geany samurai-ide.ts -l 552 # < samurai-ide.ts:552:        <location filename="samurai_ide/translations.py" line="103"/>
geany samurai-ide.ts -l 558 # < samurai-ide.ts:558:        <location filename="samurai_ide/translations.py" line="104"/>
geany samurai-ide.ts -l 565 # < samurai-ide.ts:565:        <location filename="samurai_ide/translations.py" line="107"/>
geany samurai-ide.ts -l 571 # < samurai-ide.ts:571:        <location filename="samurai_ide/translations.py" line="108"/>
geany samurai-ide.ts -l 577 # < samurai-ide.ts:577:        <location filename="samurai_ide/translations.py" line="109"/>
geany samurai-ide.ts -l 583 # < samurai-ide.ts:583:        <location filename="samurai_ide/translations.py" line="110"/>
geany samurai-ide.ts -l 589 # < samurai-ide.ts:589:        <location filename="samurai_ide/translations.py" line="111"/>
geany samurai-ide.ts -l 595 # < samurai-ide.ts:595:        <location filename="samurai_ide/translations.py" line="114"/>
geany samurai-ide.ts -l 601 # < samurai-ide.ts:601:        <location filename="samurai_ide/translations.py" line="115"/>
geany samurai-ide.ts -l 607 # < samurai-ide.ts:607:        <location filename="samurai_ide/translations.py" line="116"/>
geany samurai-ide.ts -l 613 # < samurai-ide.ts:613:        <location filename="samurai_ide/translations.py" line="117"/>
geany samurai-ide.ts -l 619 # < samurai-ide.ts:619:        <location filename="samurai_ide/translations.py" line="118"/>
geany samurai-ide.ts -l 625 # < samurai-ide.ts:625:        <location filename="samurai_ide/translations.py" line="119"/>
geany samurai-ide.ts -l 631 # < samurai-ide.ts:631:        <location filename="samurai_ide/translations.py" line="120"/>
geany samurai-ide.ts -l 637 # < samurai-ide.ts:637:        <location filename="samurai_ide/translations.py" line="121"/>
geany samurai-ide.ts -l 643 # < samurai-ide.ts:643:        <location filename="samurai_ide/translations.py" line="122"/>
geany samurai-ide.ts -l 649 # < samurai-ide.ts:649:        <location filename="samurai_ide/translations.py" line="123"/>
geany samurai-ide.ts -l 655 # < samurai-ide.ts:655:        <location filename="samurai_ide/translations.py" line="124"/>
geany samurai-ide.ts -l 661 # < samurai-ide.ts:661:        <location filename="samurai_ide/translations.py" line="127"/>
geany samurai-ide.ts -l 667 # < samurai-ide.ts:667:        <location filename="samurai_ide/translations.py" line="128"/>
geany samurai-ide.ts -l 673 # < samurai-ide.ts:673:        <location filename="samurai_ide/translations.py" line="129"/>
geany samurai-ide.ts -l 679 # < samurai-ide.ts:679:        <location filename="samurai_ide/translations.py" line="130"/>
geany samurai-ide.ts -l 685 # < samurai-ide.ts:685:        <location filename="samurai_ide/translations.py" line="131"/>
geany samurai-ide.ts -l 691 # < samurai-ide.ts:691:        <location filename="samurai_ide/translations.py" line="135"/>
geany samurai-ide.ts -l 697 # < samurai-ide.ts:697:        <location filename="samurai_ide/translations.py" line="136"/>
geany samurai-ide.ts -l 703 # < samurai-ide.ts:703:        <location filename="samurai_ide/translations.py" line="137"/>
geany samurai-ide.ts -l 709 # < samurai-ide.ts:709:        <location filename="samurai_ide/translations.py" line="138"/>
geany samurai-ide.ts -l 715 # < samurai-ide.ts:715:        <location filename="samurai_ide/translations.py" line="139"/>
geany samurai-ide.ts -l 721 # < samurai-ide.ts:721:        <location filename="samurai_ide/translations.py" line="140"/>
geany samurai-ide.ts -l 727 # < samurai-ide.ts:727:        <location filename="samurai_ide/translations.py" line="141"/>
geany samurai-ide.ts -l 733 # < samurai-ide.ts:733:        <location filename="samurai_ide/translations.py" line="142"/>
geany samurai-ide.ts -l 739 # < samurai-ide.ts:739:        <location filename="samurai_ide/translations.py" line="143"/>
geany samurai-ide.ts -l 745 # < samurai-ide.ts:745:        <location filename="samurai_ide/translations.py" line="144"/>
geany samurai-ide.ts -l 751 # < samurai-ide.ts:751:        <location filename="samurai_ide/translations.py" line="409"/>
geany samurai-ide.ts -l 757 # < samurai-ide.ts:757:        <location filename="samurai_ide/translations.py" line="146"/>
geany samurai-ide.ts -l 763 # < samurai-ide.ts:763:        <location filename="samurai_ide/translations.py" line="147"/>
geany samurai-ide.ts -l 769 # < samurai-ide.ts:769:        <location filename="samurai_ide/translations.py" line="148"/>
geany samurai-ide.ts -l 775 # < samurai-ide.ts:775:        <location filename="samurai_ide/translations.py" line="149"/>
geany samurai-ide.ts -l 781 # < samurai-ide.ts:781:        <location filename="samurai_ide/translations.py" line="150"/>
geany samurai-ide.ts -l 787 # < samurai-ide.ts:787:        <location filename="samurai_ide/translations.py" line="151"/>
geany samurai-ide.ts -l 793 # < samurai-ide.ts:793:        <location filename="samurai_ide/translations.py" line="152"/>
geany samurai-ide.ts -l 799 # < samurai-ide.ts:799:        <location filename="samurai_ide/translations.py" line="153"/>
geany samurai-ide.ts -l 805 # < samurai-ide.ts:805:        <location filename="samurai_ide/translations.py" line="154"/>
geany samurai-ide.ts -l 811 # < samurai-ide.ts:811:        <location filename="samurai_ide/translations.py" line="623"/>
geany samurai-ide.ts -l 816 # < samurai-ide.ts:816:        <location filename="samurai_ide/translations.py" line="159"/>
geany samurai-ide.ts -l 822 # < samurai-ide.ts:822:        <location filename="samurai_ide/translations.py" line="160"/>
geany samurai-ide.ts -l 828 # < samurai-ide.ts:828:        <location filename="samurai_ide/translations.py" line="161"/>
geany samurai-ide.ts -l 834 # < samurai-ide.ts:834:        <location filename="samurai_ide/translations.py" line="162"/>
geany samurai-ide.ts -l 840 # < samurai-ide.ts:840:        <location filename="samurai_ide/translations.py" line="165"/>
geany samurai-ide.ts -l 846 # < samurai-ide.ts:846:        <location filename="samurai_ide/translations.py" line="166"/>
geany samurai-ide.ts -l 852 # < samurai-ide.ts:852:        <location filename="samurai_ide/translations.py" line="412"/>
geany samurai-ide.ts -l 858 # < samurai-ide.ts:858:        <location filename="samurai_ide/translations.py" line="168"/>
geany samurai-ide.ts -l 864 # < samurai-ide.ts:864:        <location filename="samurai_ide/translations.py" line="169"/>
geany samurai-ide.ts -l 870 # < samurai-ide.ts:870:        <location filename="samurai_ide/translations.py" line="172"/>
geany samurai-ide.ts -l 876 # < samurai-ide.ts:876:        <location filename="samurai_ide/translations.py" line="175"/>
geany samurai-ide.ts -l 882 # < samurai-ide.ts:882:        <location filename="samurai_ide/translations.py" line="176"/>
geany samurai-ide.ts -l 888 # < samurai-ide.ts:888:        <location filename="samurai_ide/translations.py" line="179"/>
geany samurai-ide.ts -l 894 # < samurai-ide.ts:894:        <location filename="samurai_ide/translations.py" line="186"/>
geany samurai-ide.ts -l 900 # < samurai-ide.ts:900:        <location filename="samurai_ide/translations.py" line="195"/>
geany samurai-ide.ts -l 906 # < samurai-ide.ts:906:        <location filename="samurai_ide/translations.py" line="201"/>
geany samurai-ide.ts -l 912 # < samurai-ide.ts:912:        <location filename="samurai_ide/translations.py" line="202"/>
geany samurai-ide.ts -l 918 # < samurai-ide.ts:918:        <location filename="samurai_ide/translations.py" line="203"/>
geany samurai-ide.ts -l 924 # < samurai-ide.ts:924:        <location filename="samurai_ide/translations.py" line="204"/>
geany samurai-ide.ts -l 930 # < samurai-ide.ts:930:        <location filename="samurai_ide/translations.py" line="205"/>
geany samurai-ide.ts -l 936 # < samurai-ide.ts:936:        <location filename="samurai_ide/translations.py" line="208"/>
geany samurai-ide.ts -l 942 # < samurai-ide.ts:942:        <location filename="samurai_ide/translations.py" line="211"/>
geany samurai-ide.ts -l 948 # < samurai-ide.ts:948:        <location filename="samurai_ide/translations.py" line="212"/>
geany samurai-ide.ts -l 954 # < samurai-ide.ts:954:        <location filename="samurai_ide/translations.py" line="213"/>
geany samurai-ide.ts -l 960 # < samurai-ide.ts:960:        <location filename="samurai_ide/translations.py" line="214"/>
geany samurai-ide.ts -l 966 # < samurai-ide.ts:966:        <location filename="samurai_ide/translations.py" line="215"/>
geany samurai-ide.ts -l 972 # < samurai-ide.ts:972:        <location filename="samurai_ide/translations.py" line="218"/>
geany samurai-ide.ts -l 978 # < samurai-ide.ts:978:        <location filename="samurai_ide/translations.py" line="221"/>
geany samurai-ide.ts -l 984 # < samurai-ide.ts:984:        <location filename="samurai_ide/translations.py" line="225"/>
geany samurai-ide.ts -l 990 # < samurai-ide.ts:990:        <location filename="samurai_ide/translations.py" line="226"/>
geany samurai-ide.ts -l 998 # < samurai-ide.ts:998:        <location filename="samurai_ide/translations.py" line="229"/>
geany samurai-ide.ts -l 1004 # < samurai-ide.ts:1004:        <location filename="samurai_ide/translations.py" line="233"/>
geany samurai-ide.ts -l 1010 # < samurai-ide.ts:1010:        <location filename="samurai_ide/translations.py" line="234"/>
geany samurai-ide.ts -l 1016 # < samurai-ide.ts:1016:        <location filename="samurai_ide/translations.py" line="238"/>
geany samurai-ide.ts -l 1022 # < samurai-ide.ts:1022:        <location filename="samurai_ide/translations.py" line="239"/>
geany samurai-ide.ts -l 1028 # < samurai-ide.ts:1028:        <location filename="samurai_ide/translations.py" line="240"/>
geany samurai-ide.ts -l 1034 # < samurai-ide.ts:1034:        <location filename="samurai_ide/translations.py" line="244"/>
geany samurai-ide.ts -l 1040 # < samurai-ide.ts:1040:        <location filename="samurai_ide/translations.py" line="245"/>
geany samurai-ide.ts -l 1046 # < samurai-ide.ts:1046:        <location filename="samurai_ide/translations.py" line="246"/>
geany samurai-ide.ts -l 1055 # < samurai-ide.ts:1055:        <location filename="samurai_ide/translations.py" line="254"/>
geany samurai-ide.ts -l 1061 # < samurai-ide.ts:1061:        <location filename="samurai_ide/translations.py" line="255"/>
geany samurai-ide.ts -l 1067 # < samurai-ide.ts:1067:        <location filename="samurai_ide/translations.py" line="256"/>
geany samurai-ide.ts -l 1073 # < samurai-ide.ts:1073:        <location filename="samurai_ide/translations.py" line="258"/>
geany samurai-ide.ts -l 1079 # < samurai-ide.ts:1079:        <location filename="samurai_ide/translations.py" line="259"/>
geany samurai-ide.ts -l 1086 # < samurai-ide.ts:1086:        <location filename="samurai_ide/translations.py" line="263"/>
geany samurai-ide.ts -l 1092 # < samurai-ide.ts:1092:        <location filename="samurai_ide/translations.py" line="264"/>
geany samurai-ide.ts -l 1098 # < samurai-ide.ts:1098:        <location filename="samurai_ide/translations.py" line="267"/>
geany samurai-ide.ts -l 1104 # < samurai-ide.ts:1104:        <location filename="samurai_ide/translations.py" line="268"/>
geany samurai-ide.ts -l 1110 # < samurai-ide.ts:1110:        <location filename="samurai_ide/translations.py" line="269"/>
geany samurai-ide.ts -l 1118 # < samurai-ide.ts:1118:        <location filename="samurai_ide/translations.py" line="276"/>
geany samurai-ide.ts -l 1124 # < samurai-ide.ts:1124:        <location filename="samurai_ide/translations.py" line="277"/>
geany samurai-ide.ts -l 1130 # < samurai-ide.ts:1130:        <location filename="samurai_ide/translations.py" line="278"/>
geany samurai-ide.ts -l 1136 # < samurai-ide.ts:1136:        <location filename="samurai_ide/translations.py" line="279"/>
geany samurai-ide.ts -l 1142 # < samurai-ide.ts:1142:        <location filename="samurai_ide/translations.py" line="280"/>
geany samurai-ide.ts -l 1148 # < samurai-ide.ts:1148:        <location filename="samurai_ide/translations.py" line="281"/>
geany samurai-ide.ts -l 1154 # < samurai-ide.ts:1154:        <location filename="samurai_ide/translations.py" line="282"/>
geany samurai-ide.ts -l 1160 # < samurai-ide.ts:1160:        <location filename="samurai_ide/translations.py" line="283"/>
geany samurai-ide.ts -l 1166 # < samurai-ide.ts:1166:        <location filename="samurai_ide/translations.py" line="284"/>
geany samurai-ide.ts -l 1172 # < samurai-ide.ts:1172:        <location filename="samurai_ide/translations.py" line="285"/>
geany samurai-ide.ts -l 1178 # < samurai-ide.ts:1178:        <location filename="samurai_ide/translations.py" line="288"/>
geany samurai-ide.ts -l 1184 # < samurai-ide.ts:1184:        <location filename="samurai_ide/translations.py" line="289"/>
geany samurai-ide.ts -l 1190 # < samurai-ide.ts:1190:        <location filename="samurai_ide/translations.py" line="290"/>
geany samurai-ide.ts -l 1196 # < samurai-ide.ts:1196:        <location filename="samurai_ide/translations.py" line="291"/>
geany samurai-ide.ts -l 1202 # < samurai-ide.ts:1202:        <location filename="samurai_ide/translations.py" line="292"/>
geany samurai-ide.ts -l 1208 # < samurai-ide.ts:1208:        <location filename="samurai_ide/translations.py" line="293"/>
geany samurai-ide.ts -l 1214 # < samurai-ide.ts:1214:        <location filename="samurai_ide/translations.py" line="294"/>
geany samurai-ide.ts -l 1221 # < samurai-ide.ts:1221:        <location filename="samurai_ide/translations.py" line="298"/>
geany samurai-ide.ts -l 1227 # < samurai-ide.ts:1227:        <location filename="samurai_ide/translations.py" line="299"/>
geany samurai-ide.ts -l 1233 # < samurai-ide.ts:1233:        <location filename="samurai_ide/translations.py" line="300"/>
geany samurai-ide.ts -l 1239 # < samurai-ide.ts:1239:        <location filename="samurai_ide/translations.py" line="301"/>
geany samurai-ide.ts -l 1245 # < samurai-ide.ts:1245:        <location filename="samurai_ide/translations.py" line="302"/>
geany samurai-ide.ts -l 1251 # < samurai-ide.ts:1251:        <location filename="samurai_ide/translations.py" line="303"/>
geany samurai-ide.ts -l 1257 # < samurai-ide.ts:1257:        <location filename="samurai_ide/translations.py" line="304"/>
geany samurai-ide.ts -l 1263 # < samurai-ide.ts:1263:        <location filename="samurai_ide/translations.py" line="308"/>
geany samurai-ide.ts -l 1269 # < samurai-ide.ts:1269:        <location filename="samurai_ide/translations.py" line="309"/>
geany samurai-ide.ts -l 1275 # < samurai-ide.ts:1275:        <location filename="samurai_ide/translations.py" line="310"/>
geany samurai-ide.ts -l 1281 # < samurai-ide.ts:1281:        <location filename="samurai_ide/translations.py" line="311"/>
geany samurai-ide.ts -l 1287 # < samurai-ide.ts:1287:        <location filename="samurai_ide/translations.py" line="312"/>
geany samurai-ide.ts -l 1293 # < samurai-ide.ts:1293:        <location filename="samurai_ide/translations.py" line="601"/>
geany samurai-ide.ts -l 1299 # < samurai-ide.ts:1299:        <location filename="samurai_ide/translations.py" line="606"/>
geany samurai-ide.ts -l 1305 # < samurai-ide.ts:1305:        <location filename="samurai_ide/translations.py" line="315"/>
geany samurai-ide.ts -l 1311 # < samurai-ide.ts:1311:        <location filename="samurai_ide/translations.py" line="608"/>
geany samurai-ide.ts -l 1317 # < samurai-ide.ts:1317:        <location filename="samurai_ide/translations.py" line="610"/>
geany samurai-ide.ts -l 1323 # < samurai-ide.ts:1323:        <location filename="samurai_ide/translations.py" line="611"/>
geany samurai-ide.ts -l 1329 # < samurai-ide.ts:1329:        <location filename="samurai_ide/translations.py" line="612"/>
geany samurai-ide.ts -l 1335 # < samurai-ide.ts:1335:        <location filename="samurai_ide/translations.py" line="613"/>
geany samurai-ide.ts -l 1341 # < samurai-ide.ts:1341:        <location filename="samurai_ide/translations.py" line="614"/>
geany samurai-ide.ts -l 1347 # < samurai-ide.ts:1347:        <location filename="samurai_ide/translations.py" line="322"/>
geany samurai-ide.ts -l 1353 # < samurai-ide.ts:1353:        <location filename="samurai_ide/translations.py" line="323"/>
geany samurai-ide.ts -l 1359 # < samurai-ide.ts:1359:        <location filename="samurai_ide/translations.py" line="324"/>
geany samurai-ide.ts -l 1365 # < samurai-ide.ts:1365:        <location filename="samurai_ide/translations.py" line="325"/>
geany samurai-ide.ts -l 1371 # < samurai-ide.ts:1371:        <location filename="samurai_ide/translations.py" line="326"/>
geany samurai-ide.ts -l 1377 # < samurai-ide.ts:1377:        <location filename="samurai_ide/translations.py" line="618"/>
geany samurai-ide.ts -l 1383 # < samurai-ide.ts:1383:        <location filename="samurai_ide/translations.py" line="328"/>
geany samurai-ide.ts -l 1389 # < samurai-ide.ts:1389:        <location filename="samurai_ide/translations.py" line="329"/>
geany samurai-ide.ts -l 1395 # < samurai-ide.ts:1395:        <location filename="samurai_ide/translations.py" line="330"/>
geany samurai-ide.ts -l 1401 # < samurai-ide.ts:1401:        <location filename="samurai_ide/translations.py" line="331"/>
geany samurai-ide.ts -l 1407 # < samurai-ide.ts:1407:        <location filename="samurai_ide/translations.py" line="332"/>
geany samurai-ide.ts -l 1413 # < samurai-ide.ts:1413:        <location filename="samurai_ide/translations.py" line="333"/>
geany samurai-ide.ts -l 1419 # < samurai-ide.ts:1419:        <location filename="samurai_ide/translations.py" line="334"/>
geany samurai-ide.ts -l 1425 # < samurai-ide.ts:1425:        <location filename="samurai_ide/translations.py" line="335"/>
geany samurai-ide.ts -l 1431 # < samurai-ide.ts:1431:        <location filename="samurai_ide/translations.py" line="336"/>
geany samurai-ide.ts -l 1437 # < samurai-ide.ts:1437:        <location filename="samurai_ide/translations.py" line="337"/>
geany samurai-ide.ts -l 1443 # < samurai-ide.ts:1443:        <location filename="samurai_ide/translations.py" line="338"/>
geany samurai-ide.ts -l 1449 # < samurai-ide.ts:1449:        <location filename="samurai_ide/translations.py" line="339"/>
geany samurai-ide.ts -l 1455 # < samurai-ide.ts:1455:        <location filename="samurai_ide/translations.py" line="340"/>
geany samurai-ide.ts -l 1461 # < samurai-ide.ts:1461:        <location filename="samurai_ide/translations.py" line="341"/>
geany samurai-ide.ts -l 1467 # < samurai-ide.ts:1467:        <location filename="samurai_ide/translations.py" line="342"/>
geany samurai-ide.ts -l 1473 # < samurai-ide.ts:1473:        <location filename="samurai_ide/translations.py" line="343"/>
geany samurai-ide.ts -l 1479 # < samurai-ide.ts:1479:        <location filename="samurai_ide/translations.py" line="344"/>
geany samurai-ide.ts -l 1485 # < samurai-ide.ts:1485:        <location filename="samurai_ide/translations.py" line="345"/>
geany samurai-ide.ts -l 1491 # < samurai-ide.ts:1491:        <location filename="samurai_ide/translations.py" line="627"/>
geany samurai-ide.ts -l 1497 # < samurai-ide.ts:1497:        <location filename="samurai_ide/translations.py" line="349"/>
geany samurai-ide.ts -l 1503 # < samurai-ide.ts:1503:        <location filename="samurai_ide/translations.py" line="630"/>
geany samurai-ide.ts -l 1509 # < samurai-ide.ts:1509:        <location filename="samurai_ide/translations.py" line="351"/>
geany samurai-ide.ts -l 1515 # < samurai-ide.ts:1515:        <location filename="samurai_ide/translations.py" line="352"/>
geany samurai-ide.ts -l 1521 # < samurai-ide.ts:1521:        <location filename="samurai_ide/translations.py" line="353"/>
geany samurai-ide.ts -l 1527 # < samurai-ide.ts:1527:        <location filename="samurai_ide/translations.py" line="633"/>
geany samurai-ide.ts -l 1533 # < samurai-ide.ts:1533:        <location filename="samurai_ide/translations.py" line="634"/>
geany samurai-ide.ts -l 1539 # < samurai-ide.ts:1539:        <location filename="samurai_ide/translations.py" line="360"/>
geany samurai-ide.ts -l 1545 # < samurai-ide.ts:1545:        <location filename="samurai_ide/translations.py" line="366"/>
geany samurai-ide.ts -l 1551 # < samurai-ide.ts:1551:        <location filename="samurai_ide/translations.py" line="367"/>
geany samurai-ide.ts -l 1557 # < samurai-ide.ts:1557:        <location filename="samurai_ide/translations.py" line="368"/>
geany samurai-ide.ts -l 1563 # < samurai-ide.ts:1563:        <location filename="samurai_ide/translations.py" line="369"/>
geany samurai-ide.ts -l 1569 # < samurai-ide.ts:1569:        <location filename="samurai_ide/translations.py" line="370"/>
geany samurai-ide.ts -l 1575 # < samurai-ide.ts:1575:        <location filename="samurai_ide/translations.py" line="371"/>
geany samurai-ide.ts -l 1581 # < samurai-ide.ts:1581:        <location filename="samurai_ide/translations.py" line="372"/>
geany samurai-ide.ts -l 1587 # < samurai-ide.ts:1587:        <location filename="samurai_ide/translations.py" line="373"/>
geany samurai-ide.ts -l 1593 # < samurai-ide.ts:1593:        <location filename="samurai_ide/translations.py" line="374"/>
geany samurai-ide.ts -l 1599 # < samurai-ide.ts:1599:        <location filename="samurai_ide/translations.py" line="375"/>
geany samurai-ide.ts -l 1605 # < samurai-ide.ts:1605:        <location filename="samurai_ide/translations.py" line="376"/>
geany samurai-ide.ts -l 1611 # < samurai-ide.ts:1611:        <location filename="samurai_ide/translations.py" line="379"/>
geany samurai-ide.ts -l 1617 # < samurai-ide.ts:1617:        <location filename="samurai_ide/translations.py" line="380"/>
geany samurai-ide.ts -l 1623 # < samurai-ide.ts:1623:        <location filename="samurai_ide/translations.py" line="647"/>
geany samurai-ide.ts -l 1629 # < samurai-ide.ts:1629:        <location filename="samurai_ide/translations.py" line="382"/>
geany samurai-ide.ts -l 1635 # < samurai-ide.ts:1635:        <location filename="samurai_ide/translations.py" line="383"/>
geany samurai-ide.ts -l 1641 # < samurai-ide.ts:1641:        <location filename="samurai_ide/translations.py" line="386"/>
geany samurai-ide.ts -l 1647 # < samurai-ide.ts:1647:        <location filename="samurai_ide/translations.py" line="387"/>
geany samurai-ide.ts -l 1653 # < samurai-ide.ts:1653:        <location filename="samurai_ide/translations.py" line="390"/>
geany samurai-ide.ts -l 1659 # < samurai-ide.ts:1659:        <location filename="samurai_ide/translations.py" line="391"/>
geany samurai-ide.ts -l 1665 # < samurai-ide.ts:1665:        <location filename="samurai_ide/translations.py" line="393"/>
geany samurai-ide.ts -l 1671 # < samurai-ide.ts:1671:        <location filename="samurai_ide/translations.py" line="395"/>
geany samurai-ide.ts -l 1677 # < samurai-ide.ts:1677:        <location filename="samurai_ide/translations.py" line="396"/>
geany samurai-ide.ts -l 1683 # < samurai-ide.ts:1683:        <location filename="samurai_ide/translations.py" line="397"/>
geany samurai-ide.ts -l 1689 # < samurai-ide.ts:1689:        <location filename="samurai_ide/translations.py" line="398"/>
geany samurai-ide.ts -l 1695 # < samurai-ide.ts:1695:        <location filename="samurai_ide/translations.py" line="399"/>
geany samurai-ide.ts -l 1701 # < samurai-ide.ts:1701:        <location filename="samurai_ide/translations.py" line="400"/>
geany samurai-ide.ts -l 1707 # < samurai-ide.ts:1707:        <location filename="samurai_ide/translations.py" line="401"/>
geany samurai-ide.ts -l 1713 # < samurai-ide.ts:1713:        <location filename="samurai_ide/translations.py" line="403"/>
geany samurai-ide.ts -l 1719 # < samurai-ide.ts:1719:        <location filename="samurai_ide/translations.py" line="404"/>
geany samurai-ide.ts -l 1725 # < samurai-ide.ts:1725:        <location filename="samurai_ide/translations.py" line="405"/>
geany samurai-ide.ts -l 1731 # < samurai-ide.ts:1731:        <location filename="samurai_ide/translations.py" line="407"/>
geany samurai-ide.ts -l 1737 # < samurai-ide.ts:1737:        <location filename="samurai_ide/translations.py" line="408"/>
geany samurai-ide.ts -l 1743 # < samurai-ide.ts:1743:        <location filename="samurai_ide/translations.py" line="410"/>
geany samurai-ide.ts -l 1749 # < samurai-ide.ts:1749:        <location filename="samurai_ide/translations.py" line="411"/>
geany samurai-ide.ts -l 1755 # < samurai-ide.ts:1755:        <location filename="samurai_ide/translations.py" line="415"/>
geany samurai-ide.ts -l 1761 # < samurai-ide.ts:1761:        <location filename="samurai_ide/translations.py" line="416"/>
geany samurai-ide.ts -l 1767 # < samurai-ide.ts:1767:        <location filename="samurai_ide/translations.py" line="419"/>
geany samurai-ide.ts -l 1773 # < samurai-ide.ts:1773:        <location filename="samurai_ide/translations.py" line="420"/>
geany samurai-ide.ts -l 1779 # < samurai-ide.ts:1779:        <location filename="samurai_ide/translations.py" line="421"/>
geany samurai-ide.ts -l 1785 # < samurai-ide.ts:1785:        <location filename="samurai_ide/translations.py" line="422"/>
geany samurai-ide.ts -l 1791 # < samurai-ide.ts:1791:        <location filename="samurai_ide/translations.py" line="423"/>
geany samurai-ide.ts -l 1797 # < samurai-ide.ts:1797:        <location filename="samurai_ide/translations.py" line="424"/>
geany samurai-ide.ts -l 1803 # < samurai-ide.ts:1803:        <location filename="samurai_ide/translations.py" line="427"/>
geany samurai-ide.ts -l 1809 # < samurai-ide.ts:1809:        <location filename="samurai_ide/translations.py" line="430"/>
geany samurai-ide.ts -l 1815 # < samurai-ide.ts:1815:        <location filename="samurai_ide/translations.py" line="433"/>
geany samurai-ide.ts -l 1821 # < samurai-ide.ts:1821:        <location filename="samurai_ide/translations.py" line="434"/>
geany samurai-ide.ts -l 1827 # < samurai-ide.ts:1827:        <location filename="samurai_ide/translations.py" line="437"/>
geany samurai-ide.ts -l 1833 # < samurai-ide.ts:1833:        <location filename="samurai_ide/translations.py" line="440"/>
geany samurai-ide.ts -l 1839 # < samurai-ide.ts:1839:        <location filename="samurai_ide/translations.py" line="443"/>
geany samurai-ide.ts -l 1845 # < samurai-ide.ts:1845:        <location filename="samurai_ide/translations.py" line="446"/>
geany samurai-ide.ts -l 1851 # < samurai-ide.ts:1851:        <location filename="samurai_ide/translations.py" line="447"/>
geany samurai-ide.ts -l 1858 # < samurai-ide.ts:1858:        <location filename="samurai_ide/translations.py" line="450"/>
geany samurai-ide.ts -l 1864 # < samurai-ide.ts:1864:        <location filename="samurai_ide/translations.py" line="453"/>
geany samurai-ide.ts -l 1870 # < samurai-ide.ts:1870:        <location filename="samurai_ide/translations.py" line="454"/>
geany samurai-ide.ts -l 1876 # < samurai-ide.ts:1876:        <location filename="samurai_ide/translations.py" line="457"/>
geany samurai-ide.ts -l 1882 # < samurai-ide.ts:1882:        <location filename="samurai_ide/translations.py" line="458"/>
geany samurai-ide.ts -l 1888 # < samurai-ide.ts:1888:        <location filename="samurai_ide/translations.py" line="459"/>
geany samurai-ide.ts -l 1894 # < samurai-ide.ts:1894:        <location filename="samurai_ide/translations.py" line="460"/>
geany samurai-ide.ts -l 1900 # < samurai-ide.ts:1900:        <location filename="samurai_ide/translations.py" line="461"/>
geany samurai-ide.ts -l 1908 # < samurai-ide.ts:1908:        <location filename="samurai_ide/translations.py" line="464"/>
geany samurai-ide.ts -l 1914 # < samurai-ide.ts:1914:        <location filename="samurai_ide/translations.py" line="465"/>
geany samurai-ide.ts -l 1920 # < samurai-ide.ts:1920:        <location filename="samurai_ide/translations.py" line="466"/>
geany samurai-ide.ts -l 1926 # < samurai-ide.ts:1926:        <location filename="samurai_ide/translations.py" line="468"/>
geany samurai-ide.ts -l 1932 # < samurai-ide.ts:1932:        <location filename="samurai_ide/translations.py" line="471"/>
geany samurai-ide.ts -l 1938 # < samurai-ide.ts:1938:        <location filename="samurai_ide/translations.py" line="474"/>
geany samurai-ide.ts -l 1944 # < samurai-ide.ts:1944:        <location filename="samurai_ide/translations.py" line="477"/>
geany samurai-ide.ts -l 1950 # < samurai-ide.ts:1950:        <location filename="samurai_ide/translations.py" line="478"/>
geany samurai-ide.ts -l 1956 # < samurai-ide.ts:1956:        <location filename="samurai_ide/translations.py" line="479"/>
geany samurai-ide.ts -l 1962 # < samurai-ide.ts:1962:        <location filename="samurai_ide/translations.py" line="480"/>
geany samurai-ide.ts -l 1968 # < samurai-ide.ts:1968:        <location filename="samurai_ide/translations.py" line="481"/>
geany samurai-ide.ts -l 1974 # < samurai-ide.ts:1974:        <location filename="samurai_ide/translations.py" line="482"/>
geany samurai-ide.ts -l 1980 # < samurai-ide.ts:1980:        <location filename="samurai_ide/translations.py" line="486"/>
geany samurai-ide.ts -l 1986 # < samurai-ide.ts:1986:        <location filename="samurai_ide/translations.py" line="487"/>
geany samurai-ide.ts -l 1992 # < samurai-ide.ts:1992:        <location filename="samurai_ide/translations.py" line="488"/>
geany samurai-ide.ts -l 1998 # < samurai-ide.ts:1998:        <location filename="samurai_ide/translations.py" line="489"/>
geany samurai-ide.ts -l 2004 # < samurai-ide.ts:2004:        <location filename="samurai_ide/translations.py" line="490"/>
geany samurai-ide.ts -l 2010 # < samurai-ide.ts:2010:        <location filename="samurai_ide/translations.py" line="491"/>
geany samurai-ide.ts -l 2016 # < samurai-ide.ts:2016:        <location filename="samurai_ide/translations.py" line="492"/>
geany samurai-ide.ts -l 2022 # < samurai-ide.ts:2022:        <location filename="samurai_ide/translations.py" line="495"/>
geany samurai-ide.ts -l 2028 # < samurai-ide.ts:2028:        <location filename="samurai_ide/translations.py" line="496"/>
geany samurai-ide.ts -l 2034 # < samurai-ide.ts:2034:        <location filename="samurai_ide/translations.py" line="497"/>
geany samurai-ide.ts -l 2040 # < samurai-ide.ts:2040:        <location filename="samurai_ide/translations.py" line="498"/>
geany samurai-ide.ts -l 2046 # < samurai-ide.ts:2046:        <location filename="samurai_ide/translations.py" line="499"/>
geany samurai-ide.ts -l 2052 # < samurai-ide.ts:2052:        <location filename="samurai_ide/translations.py" line="500"/>
geany samurai-ide.ts -l 2058 # < samurai-ide.ts:2058:        <location filename="samurai_ide/translations.py" line="501"/>
geany samurai-ide.ts -l 2064 # < samurai-ide.ts:2064:        <location filename="samurai_ide/translations.py" line="502"/>
geany samurai-ide.ts -l 2070 # < samurai-ide.ts:2070:        <location filename="samurai_ide/translations.py" line="508"/>
geany samurai-ide.ts -l 2076 # < samurai-ide.ts:2076:        <location filename="samurai_ide/translations.py" line="509"/>
geany samurai-ide.ts -l 2082 # < samurai-ide.ts:2082:        <location filename="samurai_ide/translations.py" line="512"/>
geany samurai-ide.ts -l 2088 # < samurai-ide.ts:2088:        <location filename="samurai_ide/translations.py" line="515"/>
geany samurai-ide.ts -l 2094 # < samurai-ide.ts:2094:        <location filename="samurai_ide/translations.py" line="516"/>
geany samurai-ide.ts -l 2100 # < samurai-ide.ts:2100:        <location filename="samurai_ide/translations.py" line="517"/>
geany samurai-ide.ts -l 2106 # < samurai-ide.ts:2106:        <location filename="samurai_ide/translations.py" line="518"/>
geany samurai-ide.ts -l 2112 # < samurai-ide.ts:2112:        <location filename="samurai_ide/translations.py" line="519"/>
geany samurai-ide.ts -l 2118 # < samurai-ide.ts:2118:        <location filename="samurai_ide/translations.py" line="520"/>
geany samurai-ide.ts -l 2124 # < samurai-ide.ts:2124:        <location filename="samurai_ide/translations.py" line="521"/>
geany samurai-ide.ts -l 2130 # < samurai-ide.ts:2130:        <location filename="samurai_ide/translations.py" line="522"/>
geany samurai-ide.ts -l 2136 # < samurai-ide.ts:2136:        <location filename="samurai_ide/translations.py" line="523"/>
geany samurai-ide.ts -l 2142 # < samurai-ide.ts:2142:        <location filename="samurai_ide/translations.py" line="524"/>
geany samurai-ide.ts -l 2148 # < samurai-ide.ts:2148:        <location filename="samurai_ide/translations.py" line="525"/>
geany samurai-ide.ts -l 2154 # < samurai-ide.ts:2154:        <location filename="samurai_ide/translations.py" line="526"/>
geany samurai-ide.ts -l 2160 # < samurai-ide.ts:2160:        <location filename="samurai_ide/translations.py" line="529"/>
geany samurai-ide.ts -l 2166 # < samurai-ide.ts:2166:        <location filename="samurai_ide/translations.py" line="532"/>
geany samurai-ide.ts -l 2172 # < samurai-ide.ts:2172:        <location filename="samurai_ide/translations.py" line="533"/>
geany samurai-ide.ts -l 2178 # < samurai-ide.ts:2178:        <location filename="samurai_ide/translations.py" line="534"/>
geany samurai-ide.ts -l 2184 # < samurai-ide.ts:2184:        <location filename="samurai_ide/translations.py" line="535"/>
geany samurai-ide.ts -l 2190 # < samurai-ide.ts:2190:        <location filename="samurai_ide/translations.py" line="536"/>
geany samurai-ide.ts -l 2196 # < samurai-ide.ts:2196:        <location filename="samurai_ide/translations.py" line="540"/>
geany samurai-ide.ts -l 2202 # < samurai-ide.ts:2202:        <location filename="samurai_ide/translations.py" line="541"/>
geany samurai-ide.ts -l 2208 # < samurai-ide.ts:2208:        <location filename="samurai_ide/translations.py" line="544"/>
geany samurai-ide.ts -l 2214 # < samurai-ide.ts:2214:        <location filename="samurai_ide/translations.py" line="548"/>
geany samurai-ide.ts -l 2220 # < samurai-ide.ts:2220:        <location filename="samurai_ide/translations.py" line="549"/>
geany samurai-ide.ts -l 2226 # < samurai-ide.ts:2226:        <location filename="samurai_ide/translations.py" line="550"/>
geany samurai-ide.ts -l 2232 # < samurai-ide.ts:2232:        <location filename="samurai_ide/translations.py" line="551"/>
geany samurai-ide.ts -l 2238 # < samurai-ide.ts:2238:        <location filename="samurai_ide/translations.py" line="552"/>
geany samurai-ide.ts -l 2244 # < samurai-ide.ts:2244:        <location filename="samurai_ide/translations.py" line="553"/>
geany samurai-ide.ts -l 2250 # < samurai-ide.ts:2250:        <location filename="samurai_ide/translations.py" line="554"/>
geany samurai-ide.ts -l 2256 # < samurai-ide.ts:2256:        <location filename="samurai_ide/translations.py" line="555"/>
geany samurai-ide.ts -l 2262 # < samurai-ide.ts:2262:        <location filename="samurai_ide/translations.py" line="556"/>
geany samurai-ide.ts -l 2268 # < samurai-ide.ts:2268:        <location filename="samurai_ide/translations.py" line="557"/>
geany samurai-ide.ts -l 2274 # < samurai-ide.ts:2274:        <location filename="samurai_ide/translations.py" line="558"/>
geany samurai-ide.ts -l 2280 # < samurai-ide.ts:2280:        <location filename="samurai_ide/translations.py" line="559"/>
geany samurai-ide.ts -l 2286 # < samurai-ide.ts:2286:        <location filename="samurai_ide/translations.py" line="560"/>
geany samurai-ide.ts -l 2292 # < samurai-ide.ts:2292:        <location filename="samurai_ide/translations.py" line="561"/>
geany samurai-ide.ts -l 2298 # < samurai-ide.ts:2298:        <location filename="samurai_ide/translations.py" line="562"/>
geany samurai-ide.ts -l 2304 # < samurai-ide.ts:2304:        <location filename="samurai_ide/translations.py" line="565"/>
geany samurai-ide.ts -l 2310 # < samurai-ide.ts:2310:        <location filename="samurai_ide/translations.py" line="566"/>
geany samurai-ide.ts -l 2317 # < samurai-ide.ts:2317:        <location filename="samurai_ide/translations.py" line="573"/>
geany samurai-ide.ts -l 2323 # < samurai-ide.ts:2323:        <location filename="samurai_ide/translations.py" line="574"/>
geany samurai-ide.ts -l 2329 # < samurai-ide.ts:2329:        <location filename="samurai_ide/translations.py" line="578"/>
geany samurai-ide.ts -l 2335 # < samurai-ide.ts:2335:        <location filename="samurai_ide/translations.py" line="579"/>
geany samurai-ide.ts -l 2341 # < samurai-ide.ts:2341:        <location filename="samurai_ide/translations.py" line="580"/>
geany samurai-ide.ts -l 2347 # < samurai-ide.ts:2347:        <location filename="samurai_ide/translations.py" line="581"/>
geany samurai-ide.ts -l 2353 # < samurai-ide.ts:2353:        <location filename="samurai_ide/translations.py" line="582"/>
geany samurai-ide.ts -l 2359 # < samurai-ide.ts:2359:        <location filename="samurai_ide/translations.py" line="583"/>
geany samurai-ide.ts -l 2365 # < samurai-ide.ts:2365:        <location filename="samurai_ide/translations.py" line="584"/>
geany samurai-ide.ts -l 2372 # < samurai-ide.ts:2372:        <location filename="samurai_ide/translations.py" line="587"/>
geany samurai-ide.ts -l 2378 # < samurai-ide.ts:2378:        <location filename="samurai_ide/translations.py" line="588"/>
geany samurai-ide.ts -l 2384 # < samurai-ide.ts:2384:        <location filename="samurai_ide/translations.py" line="594"/>
geany samurai-ide.ts -l 2390 # < samurai-ide.ts:2390:        <location filename="samurai_ide/translations.py" line="595"/>
geany samurai-ide.ts -l 2396 # < samurai-ide.ts:2396:        <location filename="samurai_ide/translations.py" line="596"/>
geany samurai-ide.ts -l 2402 # < samurai-ide.ts:2402:        <location filename="samurai_ide/translations.py" line="597"/>
geany samurai-ide.ts -l 2408 # < samurai-ide.ts:2408:        <location filename="samurai_ide/translations.py" line="598"/>
geany samurai-ide.ts -l 2414 # < samurai-ide.ts:2414:        <location filename="samurai_ide/translations.py" line="599"/>
geany samurai-ide.ts -l 2420 # < samurai-ide.ts:2420:        <location filename="samurai_ide/translations.py" line="600"/>
geany samurai-ide.ts -l 2426 # < samurai-ide.ts:2426:        <location filename="samurai_ide/translations.py" line="602"/>
geany samurai-ide.ts -l 2432 # < samurai-ide.ts:2432:        <location filename="samurai_ide/translations.py" line="603"/>
geany samurai-ide.ts -l 2438 # < samurai-ide.ts:2438:        <location filename="samurai_ide/translations.py" line="604"/>
geany samurai-ide.ts -l 2444 # < samurai-ide.ts:2444:        <location filename="samurai_ide/translations.py" line="605"/>
geany samurai-ide.ts -l 2450 # < samurai-ide.ts:2450:        <location filename="samurai_ide/translations.py" line="607"/>
geany samurai-ide.ts -l 2456 # < samurai-ide.ts:2456:        <location filename="samurai_ide/translations.py" line="609"/>
geany samurai-ide.ts -l 2462 # < samurai-ide.ts:2462:        <location filename="samurai_ide/translations.py" line="615"/>
geany samurai-ide.ts -l 2468 # < samurai-ide.ts:2468:        <location filename="samurai_ide/translations.py" line="616"/>
geany samurai-ide.ts -l 2474 # < samurai-ide.ts:2474:        <location filename="samurai_ide/translations.py" line="617"/>
geany samurai-ide.ts -l 2480 # < samurai-ide.ts:2480:        <location filename="samurai_ide/translations.py" line="619"/>
geany samurai-ide.ts -l 2486 # < samurai-ide.ts:2486:        <location filename="samurai_ide/translations.py" line="620"/>
geany samurai-ide.ts -l 2492 # < samurai-ide.ts:2492:        <location filename="samurai_ide/translations.py" line="621"/>
geany samurai-ide.ts -l 2498 # < samurai-ide.ts:2498:        <location filename="samurai_ide/translations.py" line="624"/>
geany samurai-ide.ts -l 2504 # < samurai-ide.ts:2504:        <location filename="samurai_ide/translations.py" line="625"/>
geany samurai-ide.ts -l 2510 # < samurai-ide.ts:2510:        <location filename="samurai_ide/translations.py" line="626"/>
geany samurai-ide.ts -l 2516 # < samurai-ide.ts:2516:        <location filename="samurai_ide/translations.py" line="631"/>
geany samurai-ide.ts -l 2522 # < samurai-ide.ts:2522:        <location filename="samurai_ide/translations.py" line="632"/>
geany samurai-ide.ts -l 2528 # < samurai-ide.ts:2528:        <location filename="samurai_ide/translations.py" line="637"/>
geany samurai-ide.ts -l 2534 # < samurai-ide.ts:2534:        <location filename="samurai_ide/translations.py" line="638"/>
geany samurai-ide.ts -l 2540 # < samurai-ide.ts:2540:        <location filename="samurai_ide/translations.py" line="639"/>
geany samurai-ide.ts -l 2546 # < samurai-ide.ts:2546:        <location filename="samurai_ide/translations.py" line="640"/>
geany samurai-ide.ts -l 2552 # < samurai-ide.ts:2552:        <location filename="samurai_ide/translations.py" line="641"/>
geany samurai-ide.ts -l 2558 # < samurai-ide.ts:2558:        <location filename="samurai_ide/translations.py" line="642"/>
geany samurai-ide.ts -l 2564 # < samurai-ide.ts:2564:        <location filename="samurai_ide/translations.py" line="645"/>
geany samurai-ide.ts -l 2570 # < samurai-ide.ts:2570:        <location filename="samurai_ide/translations.py" line="646"/>
geany samurai-ide.ts -l 2576 # < samurai-ide.ts:2576:        <location filename="samurai_ide/translations.py" line="648"/>
geany samurai-ide.ts -l 2582 # < samurai-ide.ts:2582:        <location filename="samurai_ide/translations.py" line="651"/>
geany samurai-ide.ts -l 2588 # < samurai-ide.ts:2588:        <location filename="samurai_ide/translations.py" line="652"/>
geany samurai-ide.ts -l 2594 # < samurai-ide.ts:2594:        <location filename="samurai_ide/translations.py" line="655"/>
geany samurai-ide.ts -l 2600 # < samurai-ide.ts:2600:        <location filename="samurai_ide/translations.py" line="658"/>
geany samurai-ide.ts -l 2606 # < samurai-ide.ts:2606:        <location filename="samurai_ide/translations.py" line="661"/>
geany samurai-ide.ts -l 2612 # < samurai-ide.ts:2612:        <location filename="samurai_ide/translations.py" line="662"/>
geany samurai-ide.ts -l 2618 # < samurai-ide.ts:2618:        <location filename="samurai_ide/translations.py" line="665"/>
geany samurai-ide.ts -l 2624 # < samurai-ide.ts:2624:        <location filename="samurai_ide/translations.py" line="668"/>
geany samurai-ide.ts -l 2630 # < samurai-ide.ts:2630:        <location filename="samurai_ide/translations.py" line="671"/>
geany samurai-ide.ts -l 2636 # < samurai-ide.ts:2636:        <location filename="samurai_ide/translations.py" line="674"/>
geany samurai-ide.ts -l 2642 # < samurai-ide.ts:2642:        <location filename="samurai_ide/translations.py" line="677"/>
geany samurai-ide.ts -l 2648 # < samurai-ide.ts:2648:        <location filename="samurai_ide/translations.py" line="678"/>
geany samurai-ide.ts -l 2654 # < samurai-ide.ts:2654:        <location filename="samurai_ide/translations.py" line="679"/>
geany samurai-ide.ts -l 2660 # < samurai-ide.ts:2660:        <location filename="samurai_ide/translations.py" line="686"/>
geany samurai-ide.ts -l 2666 # < samurai-ide.ts:2666:        <location filename="samurai_ide/translations.py" line="687"/>
geany samurai-ide.ts -l 2672 # < samurai-ide.ts:2672:        <location filename="samurai_ide/translations.py" line="688"/>
geany samurai-ide.ts -l 2678 # < samurai-ide.ts:2678:        <location filename="samurai_ide/translations.py" line="689"/>
geany samurai-ide.ts -l 2684 # < samurai-ide.ts:2684:        <location filename="samurai_ide/translations.py" line="693"/>
geany samurai-ide.ts -l 2690 # < samurai-ide.ts:2690:        <location filename="samurai_ide/translations.py" line="694"/>
geany samurai-ide.ts -l 2696 # < samurai-ide.ts:2696:        <location filename="samurai_ide/translations.py" line="695"/>
geany samurai-ide.ts -l 2702 # < samurai-ide.ts:2702:        <location filename="samurai_ide/translations.py" line="699"/>
geany samurai-ide.ts -l 2708 # < samurai-ide.ts:2708:        <location filename="samurai_ide/translations.py" line="700"/>
geany samurai-ide.ts -l 2714 # < samurai-ide.ts:2714:        <location filename="samurai_ide/translations.py" line="701"/>
geany samurai-ide.ts -l 2721 # < samurai-ide.ts:2721:        <location filename="samurai_ide/translations.py" line="705"/>
geany samurai-ide.ts -l 2727 # < samurai-ide.ts:2727:        <location filename="samurai_ide/translations.py" line="706"/>
geany samurai-ide_translate -l 2 # < samurai-ide_translate:2:SOURCES += samurai_ide/translations.py
geany open-more.sh -l 1 # < open-more.sh:1:geany .gitignore -l 1 # < .gitignore:1:# samurai_ide specific
geany open-more.sh -l 2 # < open-more.sh:2:geany .gitignore -l 2 # < .gitignore:2:samurai_ide/addins/plugins/*
geany open-more.sh -l 3 # < open-more.sh:3:geany samurai-ide.ts -l 6 # < samurai-ide.ts:6:        <location filename="samurai_ide/translations.py" line="9"/>
